image: Visual Studio 2022

platform:
  - x64

cache:
  - node_modules
  - 'thetis20\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 23 x64
  - npm install --legacy-peer-deps

build_script:
  - npm run electron-build:win

test: off